# Generated by Django 2.0.7 on 2018-07-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180719_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='bday',
        ),
    ]
