# Generated by Django 2.0.7 on 2018-07-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180719_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
